[tox]
min_version = 4.0
isolated_build = true
env_list = py313, py314
skip_missing_interpreters = true

[testenv]
description = run tests
package = wheel
wheel_build_env = .pkg
deps =
    uv
commands =
    uv run pytest --cov=katharos --cov-fail-under=80 {posargs}